<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wls.server.com" ignored="0" name="calc" tests="7" failures="1" timestamp="2020-09-27T14:23:23 IST" time="0.097" errors="0">
  <testcase name="divisionByZeroTest" time="0.001" classname="org.demo.app.CalculatorTest"/>
  <testcase name="divisionTest" time="0.005" classname="org.demo.app.CalculatorTest"/>
  <testcase name="exampleTest" time="0.0" classname="org.demo.app.CalculatorTest"/>
  <testcase name="mult" time="0.0" classname="org.demo.app.CalculatorTest"/>
  <testcase name="substractionFailTest" time="0.001" classname="org.demo.app.CalculatorTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at org.demo.app.CalculatorTest.substractionFailTest(CalculatorTest.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- substractionFailTest -->
  <testcase name="substractionTest" time="0.001" classname="org.demo.app.CalculatorTest"/>
  <testcase name="sumTest" time="0.0" classname="org.demo.app.CalculatorTest"/>
</testsuite> <!-- calc -->
