<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="calculator" duration-ms="97" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
    <groups>
    </groups>
    <test name="calc" duration-ms="97" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
      <class name="org.demo.app.CalculatorTest">
        <test-method status="PASS" signature="init()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="init" is-config="true" duration-ms="13" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="divisionByZeroTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="divisionByZeroTest" duration-ms="1" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[Division can't be perform!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: Division can't be perform!
at org.demo.app.Calculator.divison(Calculator.java:26)
at org.demo.app.CalculatorTest.divisionByZeroTest(CalculatorTest.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divisionByZeroTest -->
        <test-method status="PASS" signature="divisionTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="divisionTest" duration-ms="5" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divisionTest -->
        <test-method status="PASS" signature="exampleTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="exampleTest" duration-ms="0" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exampleTest -->
        <test-method status="PASS" signature="mult()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="mult" duration-ms="0" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mult -->
        <test-method status="FAIL" signature="substractionFailTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="substractionFailTest" duration-ms="1" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at org.demo.app.CalculatorTest.substractionFailTest(CalculatorTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- substractionFailTest -->
        <test-method status="PASS" signature="substractionTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="substractionTest" duration-ms="1" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- substractionTest -->
        <test-method status="PASS" signature="sumTest()[pri:0, instance:org.demo.app.CalculatorTest@5dfcfece]" name="sumTest" duration-ms="0" started-at="2020-09-27T14:23:23 IST" finished-at="2020-09-27T14:23:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumTest -->
      </class> <!-- org.demo.app.CalculatorTest -->
    </test> <!-- calc -->
  </suite> <!-- calculator -->
</testng-results>
